# Generated by Django 6.0.5 on 2026-05-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_participacaogrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='funcoes_disponiveis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participacaogrupo',
            name='anotacao_aluno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participacaogrupo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos_alunos/'),
        ),
    ]
