# Generated by Django 6.0.5 on 2026-05-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mensagemgrupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='data_fim',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
    ]
